default: compile test
compile:
	javac -Xbootclasspath:/usr/lib/jvm/java-1.6.0-openjdk-i386/jre/lib/rt.jar -source 1.6 -target 1.6 WorkerTest/Worker.java
test: compile
	javac -Xbootclasspath:/usr/lib/jvm/java-1.6.0-openjdk-i386/jre/lib/rt.jar -source 1.6 -target 1.6 WorkerTest.java